### ISSUE TITLE
Add The ~roll Command

### ISSUE THREAD

**Issue by AlexMassenzio** [AlexMassenzio/RedBot#6]
- [ ] By default, the command should return a random number from 1 to 100
- [x] Allow one optional parameter named modifier.
  - [ ] If the modifier is only an integer, then change the upper bounds to modifier.
  - [x] The command should accept dice notation (d20, 2d5, etc)

**Comment by richardkopelow** [comment]
I know it doesn't say help wanted, but I would be happy to take this for a spin.

**Comment by richardkopelow** [comment]
and would "dice notation" include arithmetic like d20+4 or d6+d4?
Also, would you prefer this go in the UtilityCommands file or in the InitializeCommands function like you mentioned in the how-to-contribute document?

**Comment by AlexMassenzio** [comment]
Hey @richardkopelow! Since the last commit, I have changed quite a bit of the structure so the wiki is pretty out of date. (EDIT: It is now up-to-date)

As for the dice notation, I originally wasn't going to add extra parts like that, but if you feel up to the challenge I will not stop you ;)

**Comment by AlexMassenzio** [comment]
You can put it straight into UtilityCommands as well :)

**Comment by richardkopelow** [comment]
How do I test the program? I am pretty sure I have the command done, but when I ran the program it started asking me questions I didn't have the answer to.

**Comment by AlexMassenzio** [comment]
You can generate a new bot here: https://discordapp.com/developers/applications/me to get a token. You can either add it to your own server or the C2GS server.

**Comment by AlexMassenzio** [comment]
Merged, gonna quickly test it on my side.

**Comment by AlexMassenzio** [comment]
Integer modifier and default still need to be implemented.

**Comment by AlexMassenzio** [comment]
Won't be able to test the new merge until tonight.

**Comment by AlexMassenzio** [comment]
Sorry for the wait! I'll be testing it right after class!

**Comment by AlexMassenzio** [comment]
Looks good @richardkopelow ! Thanks for the help!
